
---
services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  # Test building Dockerfile.
  - docker build -t docker-ansible-amzlinux2 .

  # Test running the container.
  - docker run --name amzlinux2-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible-amzlinux2
  # Verify Ansible is available in the container.
  - docker exec --tty amzlinux2-container env TERM=xterm ansible --version